# Dove common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly DOVE_ENV_OVERRIDE="${DOVE_ROOT}/env_override.sh"
if [[ -f "${DOVE_ENV_OVERRIDE}" ]]; then
    source "${DOVE_ENV_OVERRIDE}"
fi

# Dove

# Scripts directory
readonly export DOVE_SCRIPTS="${DOVE_ROOT}/scripts"

# Set our platform, OS, and architecture
readonly export DOVE_ENV_HELPERS="${DOVE_SCRIPTS}/env_helpers.sh"
source "${DOVE_ENV_HELPERS}"

# Whether we're being invoked from a Nix flake
readonly DOVE_NIX_DEFAULT=0
if [[ -z "${DOVE_NIX+x}" ]]; then
    export DOVE_NIX="${DOVE_NIX_DEFAULT}"
fi

# Nix flakes should only build their respective platform
if [ "${DOVE_NIX}" == 1 ]; then
    if [ "${DOVE_OS}" == 'osx' ]; then
        export DOVE_OSX_ONLY=1
    else
        export DOVE_LINUX_ONLY=1
    fi
fi

# Version info
readonly export DOVE_VERSIONS="${DOVE_SCRIPTS}/versions.sh"

# Archives directory
readonly export DOVE_ARCHIVES="${DOVE_ROOT}/archives"

# Build directory
readonly DOVE_BUILD_DEFAULT="${DOVE_ROOT}/build"
if [[ -z "${DOVE_BUILD+x}" ]]; then
    if [ "${DOVE_NIX}" == 1 ]; then
        # Nix needs to use /tmp here, see https://codeberg.org/celenity/Dove/issues/59
        export DOVE_BUILD='/tmp/dove/build'
    else
        export DOVE_BUILD="${DOVE_BUILD_DEFAULT}"
    fi
fi

# Temporary build directory
export DOVE_TEMP="${DOVE_BUILD}/tmp"

# Build resources directory
readonly export DOVE_BUILD_RESOURCES="${DOVE_ROOT}/build-resources"

# External sources directory
readonly export DOVE_EXTERNAL="${DOVE_ROOT}/external"

# External downloads/resources directory
readonly export DOVE_DOWNLOADS="${DOVE_EXTERNAL}/downloads"

# Dove outputs directory
readonly DOVE_OUTPUTS_DEFAULT="${DOVE_ROOT}"
if [[ -z "${DOVE_OUTPUTS+x}" ]]; then
    export DOVE_OUTPUTS="${DOVE_OUTPUTS_DEFAULT}"
fi

# Linux outputs directory
DOVE_LINUX_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/linux"
if [[ -z "${DOVE_LINUX_OUTPUTS+x}" ]]; then
    export DOVE_LINUX_OUTPUTS="${DOVE_LINUX_OUTPUTS_DEFAULT}"
fi

## Linux (Flatpak) outputs directory
DOVE_LINUX_FLATPAK_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/linux-flatpak"
if [[ -z "${DOVE_LINUX_FLATPAK_OUTPUTS+x}" ]]; then
    export DOVE_LINUX_FLATPAK_OUTPUTS="${DOVE_LINUX_FLATPAK_OUTPUTS_DEFAULT}"
fi

# OS X outputs directory
DOVE_OSX_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/osx"
if [[ -z "${DOVE_OSX_OUTPUTS+x}" ]]; then
    export DOVE_OSX_OUTPUTS="${DOVE_OSX_OUTPUTS_DEFAULT}"
fi

## OS X (Intel) outputs directory
DOVE_OSX_INTEL_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/osx-intel"
if [[ -z "${DOVE_OSX_INTEL_OUTPUTS+x}" ]]; then
    export DOVE_OSX_INTEL_OUTPUTS="${DOVE_OSX_INTEL_OUTPUTS_DEFAULT}"
fi

# Windows outputs directory
DOVE_WINDOWS_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/windows"
if [[ -z "${DOVE_WINDOWS_OUTPUTS+x}" ]]; then
    export DOVE_WINDOWS_OUTPUTS="${DOVE_WINDOWS_OUTPUTS_DEFAULT}"
fi

# Should we create a log file for build.sh? (Default)
readonly DOVE_LOG_BUILD_DEFAULT=1
if [[ -z "${DOVE_LOG_BUILD+x}" ]]; then
    export DOVE_LOG_BUILD="${DOVE_LOG_BUILD_DEFAULT}"
fi

# Should we create a log file for get_sources.sh? (Default)
readonly DOVE_LOG_SOURCES_DEFAULT=1
if [[ -z "${DOVE_LOG_SOURCES+x}" ]]; then
    export DOVE_LOG_SOURCES="${DOVE_LOG_SOURCES_DEFAULT}"
fi

# Directory where we should store log files (if logging is desired)
DOVE_LOG_DIR_DEFAULT="${DOVE_BUILD}/logs"
if [[ -z "${DOVE_LOG_DIR+x}" ]]; then
    export DOVE_LOG_DIR="${DOVE_LOG_DIR_DEFAULT}"
fi

# GNU awk
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_AWK_DEFAULT='gawk'
else
    readonly DOVE_AWK_DEFAULT='awk'
fi
if [[ -z "${DOVE_AWK+x}" ]]; then
    export DOVE_AWK="${DOVE_AWK_DEFAULT}"
fi

# GNU sed
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_SED_DEFAULT='gsed'
else
    readonly DOVE_SED_DEFAULT='sed'
fi
if [[ -z "${DOVE_SED+x}" ]]; then
    export DOVE_SED="${DOVE_SED_DEFAULT}"
fi

# GNU tar
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_TAR_DEFAULT='gtar'
else
    readonly DOVE_TAR_DEFAULT='tar'
fi
if [[ -z "${DOVE_TAR+x}" ]]; then
    export DOVE_TAR="${DOVE_TAR_DEFAULT}"
fi

# lxml
readonly DOVE_LXML_DEFAULT="${DOVE_EXTERNAL}/lxml"
if [[ -z "${DOVE_LXML+x}" ]]; then
    export DOVE_LXML="${DOVE_LXML_DEFAULT}"
fi

# Phoenix
readonly DOVE_PHOENIX_DEFAULT="${DOVE_EXTERNAL}/phoenix"
if [[ -z "${DOVE_PHOENIX+x}" ]]; then
    export DOVE_PHOENIX="${DOVE_PHOENIX_DEFAULT}"
fi

# pip
readonly DOVE_PIP_DEFAULT="${DOVE_EXTERNAL}/pip"
if [[ -z "${DOVE_PIP+x}" ]]; then
    export DOVE_PIP="${DOVE_PIP_DEFAULT}"
fi

# Python
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_PYTHON_DEFAULT='/opt/homebrew/bin/python'
else
    readonly DOVE_PYTHON_DEFAULT='/usr/bin/python'
fi
if [[ -z "${DOVE_PYTHON+x}" ]]; then
    export DOVE_PYTHON="${DOVE_PYTHON_DEFAULT}"
fi

# Python (pip) environment
DOVE_PIP_DIR_DEFAULT="${DOVE_BUILD}/pyenv"
if [[ -z "${DOVE_PIP_DIR+x}" ]]; then
    export DOVE_PIP_DIR="${DOVE_PIP_DIR_DEFAULT}"
fi
export DOVE_PIP_ENV="${DOVE_PIP_DIR}/bin/activate"
export DOVE_PIP_EXEC="${DOVE_PIP_DIR}/bin/pip"

# Thunderbird Autoconfiguration Database (ISPDB)
readonly DOVE_AUTOCONFIG_DEFAULT="${DOVE_EXTERNAL}/autoconfig"
if [[ -z "${DOVE_AUTOCONFIG+x}" ]]; then
    export DOVE_AUTOCONFIG="${DOVE_AUTOCONFIG_DEFAULT}"
fi

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly DOVE_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${DOVE_CURL_FLAGS_OVERRIDE+x}" ]]; then
    export DOVE_CURL_FLAGS_OVERRIDE="${DOVE_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi

# curl flags
readonly DOVE_CURL_FLAGS_DEFAULT='-q --disable --no-netrc -j -e "" -A "" -S --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --ftp-create-dirs --ftp-ssl-control --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-proxy-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ntlm --no-proxy-ssl-allow-beast --no-proxy-ssl-auto-client-cert --no-sessionid --no-skip-existing --no-ssl --no-ssl-allow-beast --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-tls-earlydata --no-xattr --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --referer "" --remove-on-error --show-error --ssl-reqd --trace-time --user-agent "" --verbose'
if [[ -z "${DOVE_CURL_FLAGS+x}" ]]; then
    export DOVE_CURL_FLAGS="${DOVE_CURL_FLAGS_DEFAULT}"
elif [[ "${DOVE_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
    export DOVE_CURL_FLAGS="${DOVE_CURL_FLAGS}"
else
    export DOVE_CURL_FLAGS="${DOVE_CURL_FLAGS_DEFAULT} ${DOVE_CURL_FLAGS}"
fi

# Whether we're ONLY building Dove for Linux
readonly DOVE_LINUX_ONLY_DEFAULT=0
if [[ -z "${DOVE_LINUX_ONLY+x}" ]]; then
    export DOVE_LINUX_ONLY="${DOVE_LINUX_ONLY_DEFAULT}"
fi
if [ "${DOVE_LINUX_ONLY}" == 1 ]; then
    export DOVE_LINUX=1
    export DOVE_LINUX_FLATPAK=0
    export DOVE_OSX=0
    export DOVE_OSX_INTEL=0
    export DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for Linux (Flatpak)
readonly DOVE_LINUX_FLATPAK_ONLY_DEFAULT=0
if [[ -z "${DOVE_LINUX_FLATPAK_ONLY+x}" ]]; then
    export DOVE_LINUX_FLATPAK_ONLY="${DOVE_LINUX_FLATPAK_ONLY_DEFAULT}"
fi
if [ "${DOVE_LINUX_FLATPAK_ONLY}" == 1 ]; then
    export DOVE_LINUX_FLATPAK=1
    export DOVE_LINUX=0
    export DOVE_OSX=0
    export DOVE_OSX_INTEL=0
    export DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for OS X
readonly DOVE_OSX_ONLY_DEFAULT=0
if [[ -z "${DOVE_OSX_ONLY+x}" ]]; then
    export DOVE_OSX_ONLY="${DOVE_OSX_ONLY_DEFAULT}"
fi
if [ "${DOVE_OSX_ONLY}" == 1 ]; then
    export DOVE_OSX=1
    export DOVE_LINUX=0
    export DOVE_LINUX_FLATPAK=0
    export DOVE_OSX_INTEL=0
    export DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for OS X (Intel)
readonly DOVE_OSX_INTEL_ONLY_DEFAULT=0
if [[ -z "${DOVE_OSX_INTEL_ONLY+x}" ]]; then
    export DOVE_OSX_INTEL_ONLY="${DOVE_OSX_INTEL_ONLY_DEFAULT}"
fi
if [ "${DOVE_OSX_INTEL_ONLY}" == 1 ]; then
    export DOVE_OSX_INTEL=1
    export DOVE_LINUX=0
    export DOVE_LINUX_FLATPAK=0
    export DOVE_OSX=0
    export DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for Windows
readonly DOVE_WINDOWS_ONLY_DEFAULT=0
if [[ -z "${DOVE_WINDOWS_ONLY+x}" ]]; then
    export DOVE_WINDOWS_ONLY="${DOVE_WINDOWS_ONLY_DEFAULT}"
fi
if [ "${DOVE_WINDOWS_ONLY}" == 1 ]; then
    export DOVE_WINDOWS=1
    export DOVE_LINUX=0
    export DOVE_LINUX_FLATPAK=0
    export DOVE_OSX=0
    export DOVE_OSX_INTEL=0
fi

# Whether we're building Dove for Linux (Default)
readonly DOVE_LINUX_DEFAULT=1
if [[ -z "${DOVE_LINUX+x}" ]]; then
    export DOVE_LINUX="${DOVE_LINUX_DEFAULT}"
fi

# Whether we're building Dove for Linux (Flatpak) (Default)
readonly DOVE_LINUX_FLATPAK_DEFAULT=1
if [[ -z "${DOVE_LINUX_FLATPAK+x}" ]]; then
    export DOVE_LINUX_FLATPAK="${DOVE_LINUX_FLATPAK_DEFAULT}"
fi

# Whether we're building Dove for OS X (Default)
readonly DOVE_OSX_DEFAULT=1
if [[ -z "${DOVE_OSX+x}" ]]; then
    export DOVE_OSX="${DOVE_OSX_DEFAULT}"
fi

# Whether we're building Dove for OS X (Intel) (Default)
readonly DOVE_OSX_INTEL_DEFAULT=1
if [[ -z "${DOVE_OSX_INTEL+x}" ]]; then
    export DOVE_OSX_INTEL="${DOVE_OSX_INTEL_DEFAULT}"
fi

# Whether we're building Dove for Windows (Default)
readonly DOVE_WINDOWS_DEFAULT=1
if [[ -z "${DOVE_WINDOWS+x}" ]]; then
    export DOVE_WINDOWS="${DOVE_WINDOWS_DEFAULT}"
fi

# Set our external environment variables
readonly DOVE_ENV_EXTERNAL="${DOVE_SCRIPTS}/env_external.sh"
source "${DOVE_ENV_EXTERNAL}"
