# Dove common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly DOVE_ENV_OVERRIDE="${DOVE_ROOT}/env_override.sh"
if [[ -f "${DOVE_ENV_OVERRIDE}" ]]; then
    source "${DOVE_ENV_OVERRIDE}"
fi

# Dove

# Scripts directory
readonly DOVE_SCRIPTS="${DOVE_ROOT}/scripts"
export DOVE_SCRIPTS

## Dove utilities
readonly DOVE_UTILS="${DOVE_SCRIPTS}/utilities.sh"
export DOVE_UTILS

# Set our platform, OS, and architecture
readonly DOVE_ENV_HELPERS="${DOVE_SCRIPTS}/env_helpers.sh"
export DOVE_ENV_HELPERS
source "${DOVE_ENV_HELPERS}"

# Whether we're being invoked from a Nix flake
readonly DOVE_NIX_DEFAULT=0
if [[ -z "${DOVE_NIX+x}" ]]; then
    DOVE_NIX="${DOVE_NIX_DEFAULT}"
fi
readonly DOVE_NIX
export DOVE_NIX

# Version info
readonly DOVE_VERSIONS="${DOVE_SCRIPTS}/versions.sh"
export DOVE_VERSIONS

# Archives directory
readonly DOVE_ARCHIVES="${DOVE_ROOT}/archives"
export DOVE_ARCHIVES

# Build directory
readonly DOVE_BUILD_DEFAULT="${DOVE_ROOT}/build"
if [[ -z "${DOVE_BUILD+x}" ]]; then
    if [ "${DOVE_NIX}" == 1 ]; then
        # Nix needs to use /tmp here, see https://codeberg.org/celenity/Dove/issues/59
        DOVE_BUILD='/tmp/dove/build'
    else
        DOVE_BUILD="${DOVE_BUILD_DEFAULT}"
    fi
fi
readonly DOVE_BUILD
export DOVE_BUILD

# Temporary build directory
readonly DOVE_TEMP="${DOVE_BUILD}/tmp"
export DOVE_TEMP

# Build resources directory
readonly DOVE_BUILD_RESOURCES="${DOVE_ROOT}/build-resources"
export DOVE_BUILD_RESOURCES

# External sources directory
readonly DOVE_EXTERNAL="${DOVE_ROOT}/external"
export DOVE_EXTERNAL

# External downloads/resources directory
readonly DOVE_DOWNLOADS="${DOVE_EXTERNAL}/downloads"
export DOVE_DOWNLOADS

# Dove outputs directory
readonly DOVE_OUTPUTS_DEFAULT="${DOVE_ROOT}"
if [[ -z "${DOVE_OUTPUTS+x}" ]]; then
    DOVE_OUTPUTS="${DOVE_OUTPUTS_DEFAULT}"
fi
readonly DOVE_OUTPUTS
export DOVE_OUTPUTS

# Linux outputs directory
readonly DOVE_LINUX_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/linux"
if [[ -z "${DOVE_LINUX_OUTPUTS+x}" ]]; then
    DOVE_LINUX_OUTPUTS="${DOVE_LINUX_OUTPUTS_DEFAULT}"
fi
readonly DOVE_LINUX_OUTPUTS
export DOVE_LINUX_OUTPUTS

## Linux (Flatpak) outputs directory
readonly DOVE_LINUX_FLATPAK_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/linux-flatpak"
if [[ -z "${DOVE_LINUX_FLATPAK_OUTPUTS+x}" ]]; then
    DOVE_LINUX_FLATPAK_OUTPUTS="${DOVE_LINUX_FLATPAK_OUTPUTS_DEFAULT}"
fi
readonly DOVE_LINUX_FLATPAK_OUTPUTS
export DOVE_LINUX_FLATPAK_OUTPUTS

# OS X outputs directory
readonly DOVE_OSX_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/osx"
if [[ -z "${DOVE_OSX_OUTPUTS+x}" ]]; then
    DOVE_OSX_OUTPUTS="${DOVE_OSX_OUTPUTS_DEFAULT}"
fi
readonly DOVE_OSX_OUTPUTS
export DOVE_OSX_OUTPUTS

## OS X (Intel) outputs directory
readonly DOVE_OSX_INTEL_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/osx-intel"
if [[ -z "${DOVE_OSX_INTEL_OUTPUTS+x}" ]]; then
    DOVE_OSX_INTEL_OUTPUTS="${DOVE_OSX_INTEL_OUTPUTS_DEFAULT}"
fi
readonly DOVE_OSX_INTEL_OUTPUTS
export DOVE_OSX_INTEL_OUTPUTS

# Windows outputs directory
readonly DOVE_WINDOWS_OUTPUTS_DEFAULT="${DOVE_OUTPUTS}/windows"
if [[ -z "${DOVE_WINDOWS_OUTPUTS+x}" ]]; then
    DOVE_WINDOWS_OUTPUTS="${DOVE_WINDOWS_OUTPUTS_DEFAULT}"
fi
readonly DOVE_WINDOWS_OUTPUTS
export DOVE_WINDOWS_OUTPUTS

# Should we create a log file for build.sh? (Default)
readonly DOVE_LOG_BUILD_DEFAULT=1
if [[ -z "${DOVE_LOG_BUILD+x}" ]]; then
    DOVE_LOG_BUILD="${DOVE_LOG_BUILD_DEFAULT}"
fi
readonly DOVE_LOG_BUILD
export DOVE_LOG_BUILD

# Should we create a log file for get_sources.sh? (Default)
readonly DOVE_LOG_SOURCES_DEFAULT=1
if [[ -z "${DOVE_LOG_SOURCES+x}" ]]; then
    DOVE_LOG_SOURCES="${DOVE_LOG_SOURCES_DEFAULT}"
fi
readonly DOVE_LOG_SOURCES
export DOVE_LOG_SOURCES

# Directory where we should store log files (if logging is desired)
readonly DOVE_LOG_DIR_DEFAULT="${DOVE_BUILD}/logs"
if [[ -z "${DOVE_LOG_DIR+x}" ]]; then
    DOVE_LOG_DIR="${DOVE_LOG_DIR_DEFAULT}"
fi
readonly DOVE_LOG_DIR
export DOVE_LOG_DIR

# GNU awk
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_AWK_DEFAULT='gawk'
else
    readonly DOVE_AWK_DEFAULT='awk'
fi
if [[ -z "${DOVE_AWK+x}" ]]; then
    DOVE_AWK="${DOVE_AWK_DEFAULT}"
fi
readonly DOVE_AWK
export DOVE_AWK

# GNU sed
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_SED_DEFAULT='gsed'
else
    readonly DOVE_SED_DEFAULT='sed'
fi
if [[ -z "${DOVE_SED+x}" ]]; then
    DOVE_SED="${DOVE_SED_DEFAULT}"
fi
readonly DOVE_SED
export DOVE_SED

# GNU tar
if [[ "${DOVE_OS}" == 'osx' ]]; then
    readonly DOVE_TAR_DEFAULT='gtar'
else
    readonly DOVE_TAR_DEFAULT='tar'
fi
if [[ -z "${DOVE_TAR+x}" ]]; then
    DOVE_TAR="${DOVE_TAR_DEFAULT}"
fi
readonly DOVE_TAR
export DOVE_TAR

# lxml
readonly DOVE_LXML_DEFAULT="${DOVE_EXTERNAL}/lxml"
if [[ -z "${DOVE_LXML+x}" ]]; then
    DOVE_LXML="${DOVE_LXML_DEFAULT}"
fi
readonly DOVE_LXML
export DOVE_LXML

# Phoenix
readonly DOVE_PHOENIX_DEFAULT="${DOVE_EXTERNAL}/phoenix"
if [[ -z "${DOVE_PHOENIX+x}" ]]; then
    DOVE_PHOENIX="${DOVE_PHOENIX_DEFAULT}"
fi
readonly DOVE_PHOENIX
export DOVE_PHOENIX

# Python
readonly DOVE_PYTHON_DIR_DEFAULT="${DOVE_EXTERNAL}/python"
if [[ -z "${DOVE_PYTHON_DIR+x}" ]]; then
    DOVE_PYTHON_DIR="${DOVE_PYTHON_DIR_DEFAULT}"
fi
readonly DOVE_PYTHON_DIR
export DOVE_PYTHON_DIR

# Python (UV) environment
readonly DOVE_PYENV_DIR_DEFAULT="${DOVE_BUILD}/pyenv"
if [[ -z "${DOVE_PYENV_DIR+x}" ]]; then
    DOVE_PYENV_DIR="${DOVE_PYENV_DIR_DEFAULT}"
fi
readonly DOVE_PYENV_DIR
readonly DOVE_PYENV="${DOVE_PYENV_DIR}/bin/activate"
export DOVE_PYENV
export DOVE_PYENV_DIR

if [[ "${DOVE_NIX}" == 1 ]]; then
    ## Nix doesn't want/need to set a specific Python path, see discussion at https://codeberg.org/celenity/Dove/issues/59
    ## and https://codeberg.org/celenity/Phoenix/issues/252
    readonly DOVE_PYTHON_DEFAULT='python'
else
    readonly DOVE_PYTHON_DEFAULT="${DOVE_PYENV_DIR}/bin/python"
fi
if [[ -z "${DOVE_PYTHON+x}" ]]; then
    DOVE_PYTHON="${DOVE_PYTHON_DEFAULT}"
fi
readonly DOVE_PYTHON
export DOVE_PYTHON

# UV
readonly DOVE_UV_DIR_DEFAULT="${DOVE_EXTERNAL}/uv"
if [[ -z "${DOVE_UV_DIR+x}" ]]; then
    DOVE_UV_DIR="${DOVE_UV_DIR_DEFAULT}"
fi
readonly DOVE_UV_DIR
readonly DOVE_UV="${DOVE_UV_DIR}/uv"
export DOVE_UV
export DOVE_UV_DIR

# UV (local directory)
readonly DOVE_UV_LOCAL_DEFAULT="${DOVE_BUILD}/uv"
if [[ -z "${DOVE_UV_LOCAL+x}" ]]; then
    DOVE_UV_LOCAL="${DOVE_UV_LOCAL_DEFAULT}"
fi
readonly DOVE_UV_LOCAL
export DOVE_UV_LOCAL

# UV cache
readonly DOVE_UV_CACHE_DEFAULT="${DOVE_UV_LOCAL}/cache"
if [[ -z "${DOVE_UV_CACHE+x}" ]]; then
    DOVE_UV_CACHE="${DOVE_UV_CACHE_DEFAULT}"
fi
readonly DOVE_UV_CACHE
export DOVE_UV_CACHE

# UV Python directory
readonly DOVE_UV_PYTHON_DEFAULT="${DOVE_UV_LOCAL}/python"
if [[ -z "${DOVE_UV_PYTHON+x}" ]]; then
    DOVE_UV_PYTHON="${DOVE_UV_PYTHON_DEFAULT}"
fi
readonly DOVE_UV_PYTHON
export DOVE_UV_PYTHON

# UV tools
readonly DOVE_UV_TOOLS_DEFAULT="${DOVE_UV_LOCAL}/tools"
if [[ -z "${DOVE_UV_TOOLS+x}" ]]; then
    DOVE_UV_TOOLS="${DOVE_UV_TOOLS_DEFAULT}"
fi
readonly DOVE_UV_TOOLS
export DOVE_UV_TOOLS

# Thunderbird Autoconfiguration Database (ISPDB)
readonly DOVE_AUTOCONFIG_DEFAULT="${DOVE_EXTERNAL}/autoconfig"
if [[ -z "${DOVE_AUTOCONFIG+x}" ]]; then
    DOVE_AUTOCONFIG="${DOVE_AUTOCONFIG_DEFAULT}"
fi
readonly DOVE_AUTOCONFIG
export DOVE_AUTOCONFIG

# Cipher suites
## (This enforces strong cipher suites - see ex. https://browserleaks.com/tls)
readonly DOVE_CIPHERS_DEFAULT='TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'
if [[ -z "${DOVE_CIPHERS+x}" ]]; then
    DOVE_CIPHERS="${DOVE_CIPHERS_DEFAULT}"
fi
readonly DOVE_CIPHERS
export DOVE_CIPHERS

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly DOVE_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${DOVE_CURL_FLAGS_OVERRIDE+x}" ]]; then
    DOVE_CURL_FLAGS_OVERRIDE="${DOVE_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly DOVE_CURL_FLAGS_OVERRIDE
export DOVE_CURL_FLAGS_OVERRIDE

# curl flags
readonly DOVE_CURL_FLAGS_DEFAULT="-q --disable --no-netrc -j -e "" -A "" -S --ciphers ${DOVE_CIPHERS} --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --ftp-create-dirs --ftp-ssl-control --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-proxy-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ntlm --no-proxy-ssl-allow-beast --no-proxy-ssl-auto-client-cert --no-sessionid --no-skip-existing --no-ssl --no-ssl-allow-beast --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-tls-earlydata --no-xattr --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --referer "" --remove-on-error --show-error --ssl-reqd --tlsv1.2 --trace-time --user-agent "" --verbose"
if [[ -z "${DOVE_CURL_FLAGS+x}" ]]; then
    readonly DOVE_CURL_FLAGS="${DOVE_CURL_FLAGS_DEFAULT}"
elif [[ "${DOVE_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
    readonly DOVE_CURL_FLAGS="${DOVE_CURL_FLAGS}"
else
    readonly DOVE_CURL_FLAGS="${DOVE_CURL_FLAGS_DEFAULT} ${DOVE_CURL_FLAGS}"
fi
export DOVE_CURL_FLAGS

# Whether we're ONLY building Dove for Linux
readonly DOVE_LINUX_ONLY_DEFAULT=0
if [ "${DOVE_NIX}" == 1 ] && [ "${DOVE_OS}" != 'osx' ]; then
    # Nix flakes should only build their respective platform
    DOVE_LINUX_ONLY=1
elif [[ -z "${DOVE_LINUX_ONLY+x}" ]]; then
    DOVE_LINUX_ONLY="${DOVE_LINUX_ONLY_DEFAULT}"
fi
readonly DOVE_LINUX_ONLY
export DOVE_LINUX_ONLY
if [ "${DOVE_LINUX_ONLY}" == 1 ]; then
    DOVE_LINUX=1
    DOVE_LINUX_FLATPAK=0
    DOVE_OSX=0
    DOVE_OSX_INTEL=0
    DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for Linux (Flatpak)
readonly DOVE_LINUX_FLATPAK_ONLY_DEFAULT=0
if [[ -z "${DOVE_LINUX_FLATPAK_ONLY+x}" ]]; then
    DOVE_LINUX_FLATPAK_ONLY="${DOVE_LINUX_FLATPAK_ONLY_DEFAULT}"
fi
readonly DOVE_LINUX_FLATPAK_ONLY
export DOVE_LINUX_FLATPAK_ONLY
if [ "${DOVE_LINUX_FLATPAK_ONLY}" == 1 ]; then
    DOVE_LINUX_FLATPAK=1
    DOVE_LINUX=0
    DOVE_OSX=0
    DOVE_OSX_INTEL=0
    DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for OS X
readonly DOVE_OSX_ONLY_DEFAULT=0
if [ "${DOVE_NIX}" == 1 ] && [ "${DOVE_OS}" == 'osx' ]; then
    # Nix flakes should only build their respective platform
    DOVE_OSX_ONLY=1
elif [[ -z "${DOVE_OSX_ONLY+x}" ]]; then
    DOVE_OSX_ONLY="${DOVE_OSX_ONLY_DEFAULT}"
fi
readonly DOVE_OSX_ONLY
export DOVE_OSX_ONLY
if [ "${DOVE_OSX_ONLY}" == 1 ]; then
    DOVE_OSX=1
    DOVE_LINUX=0
    DOVE_LINUX_FLATPAK=0
    DOVE_OSX_INTEL=0
    DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for OS X (Intel)
readonly DOVE_OSX_INTEL_ONLY_DEFAULT=0
if [[ -z "${DOVE_OSX_INTEL_ONLY+x}" ]]; then
    DOVE_OSX_INTEL_ONLY="${DOVE_OSX_INTEL_ONLY_DEFAULT}"
fi
readonly DOVE_OSX_INTEL_ONLY
export DOVE_OSX_INTEL_ONLY
if [ "${DOVE_OSX_INTEL_ONLY}" == 1 ]; then
    DOVE_OSX_INTEL=1
    DOVE_LINUX=0
    DOVE_LINUX_FLATPAK=0
    DOVE_OSX=0
    DOVE_WINDOWS=0
fi

# Whether we're ONLY building Dove for Windows
readonly DOVE_WINDOWS_ONLY_DEFAULT=0
if [[ -z "${DOVE_WINDOWS_ONLY+x}" ]]; then
    DOVE_WINDOWS_ONLY="${DOVE_WINDOWS_ONLY_DEFAULT}"
fi
readonly DOVE_WINDOWS_ONLY
export DOVE_WINDOWS_ONLY
if [ "${DOVE_WINDOWS_ONLY}" == 1 ]; then
    DOVE_WINDOWS=1
    DOVE_LINUX=0
    DOVE_LINUX_FLATPAK=0
    DOVE_OSX=0
    DOVE_OSX_INTEL=0
fi

# Whether we're building Dove for Linux (Default)
readonly DOVE_LINUX_DEFAULT=1
if [[ -z "${DOVE_LINUX+x}" ]]; then
    DOVE_LINUX="${DOVE_LINUX_DEFAULT}"
fi
readonly DOVE_LINUX
export DOVE_LINUX

# Whether we're building Dove for Linux (Flatpak) (Default)
readonly DOVE_LINUX_FLATPAK_DEFAULT=1
if [[ -z "${DOVE_LINUX_FLATPAK+x}" ]]; then
    DOVE_LINUX_FLATPAK="${DOVE_LINUX_FLATPAK_DEFAULT}"
fi
readonly DOVE_LINUX_FLATPAK
export DOVE_LINUX_FLATPAK

# Whether we're building Dove for OS X (Default)
readonly DOVE_OSX_DEFAULT=1
if [[ -z "${DOVE_OSX+x}" ]]; then
    DOVE_OSX="${DOVE_OSX_DEFAULT}"
fi
readonly DOVE_OSX
export DOVE_OSX

# Whether we're building Dove for OS X (Intel) (Default)
readonly DOVE_OSX_INTEL_DEFAULT=1
if [[ -z "${DOVE_OSX_INTEL+x}" ]]; then
    DOVE_OSX_INTEL="${DOVE_OSX_INTEL_DEFAULT}"
fi
readonly DOVE_OSX_INTEL
export DOVE_OSX_INTEL

# Whether we're building Dove for Windows (Default)
readonly DOVE_WINDOWS_DEFAULT=1
if [[ -z "${DOVE_WINDOWS+x}" ]]; then
    DOVE_WINDOWS="${DOVE_WINDOWS_DEFAULT}"
fi
readonly DOVE_WINDOWS
export DOVE_WINDOWS

# Set our external environment variables
readonly DOVE_ENV_EXTERNAL="${DOVE_SCRIPTS}/env_external.sh"
source "${DOVE_ENV_EXTERNAL}"

# We've now set our environment variables...
readonly DOVE_SET_ENVS=1
export DOVE_SET_ENVS
