# Dove external environment variables

## This is used for converting Dove-specific environment variables to ones used in external projects.

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## CAUTION: Do NOT try to configure any of these environment variables directly!
## Use the Dove equivalent variables (at `env_common.sh`) instead.

# Phoenix
readonly PHOENIX_ANDROID=0
readonly PHOENIX_EXTRA_EXTENDED_OUTPUT_FILENAME='dove'
readonly PHOENIX_EXTRA_POLICIES=1
readonly PHOENIX_EXTRA_POLICIES_LINUX=1
readonly PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK=1
readonly PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK=1
readonly PHOENIX_EXTRA_POLICIES_OSX=1
readonly PHOENIX_EXTRA_POLICIES_OSX_INTEL=1
readonly PHOENIX_EXTRA_POLICIES_OSX_SILICON=1
readonly PHOENIX_EXTRA_POLICIES_WINDOWS=1
readonly PHOENIX_EXTRA_PREFS_JS=1
readonly PHOENIX_MAIL=1
readonly PHOENIX_NIX="${DOVE_NIX}"
readonly PHOENIX_PYTHON="${DOVE_PYTHON}"
export PHOENIX_ANDROID
export PHOENIX_EXTRA_EXTENDED_OUTPUT_FILENAME
export PHOENIX_EXTRA_POLICIES
export PHOENIX_EXTRA_POLICIES_LINUX
export PHOENIX_EXTRA_POLICIES_LINUX_FLATPAK
export PHOENIX_EXTRA_POLICIES_LINUX_NONFLATPAK
export PHOENIX_EXTRA_POLICIES_OSX
export PHOENIX_EXTRA_POLICIES_OSX_INTEL
export PHOENIX_EXTRA_POLICIES_OSX_SILICON
export PHOENIX_EXTRA_POLICIES_WINDOWS
export PHOENIX_EXTRA_PREFS_JS
export PHOENIX_MAIL
export PHOENIX_NIX
export PHOENIX_PYTHON

readonly PHOENIX_EXTRA_PREFS_JS_FILE="${DOVE_TEMP}/dove-unified-parsed.js"
readonly PHOENIX_EXTRA_PREFS_JS_OUTPUT_DIR="${DOVE_TEMP}/prefs"
export PHOENIX_EXTRA_PREFS_JS_FILE
export PHOENIX_EXTRA_PREFS_JS_OUTPUT_DIR

readonly PHOENIX_EXTRA_POLICIES_FILE="${DOVE_BUILD_RESOURCES}/policies/dove-unified.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_LINUX="${DOVE_BUILD_RESOURCES}/policies/dove-linux.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_LINUX_NONFLATPAK="${DOVE_BUILD_RESOURCES}/policies/dove-linux-nonflatpak.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_LINUX_FLATPAK="${DOVE_BUILD_RESOURCES}/policies/dove-linux-flatpak.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_OSX="${DOVE_BUILD_RESOURCES}/policies/dove-osx.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_OSX_INTEL="${DOVE_BUILD_RESOURCES}/policies/dove-osx-intel.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_OSX_SILICON="${DOVE_BUILD_RESOURCES}/policies/dove-osx-silicon.json"
readonly PHOENIX_EXTRA_POLICIES_FILE_WINDOWS="${DOVE_BUILD_RESOURCES}/policies/dove-windows.json"
export PHOENIX_EXTRA_POLICIES_FILE
export PHOENIX_EXTRA_POLICIES_FILE_LINUX
export PHOENIX_EXTRA_POLICIES_FILE_LINUX_NONFLATPAK
export PHOENIX_EXTRA_POLICIES_FILE_LINUX_FLATPAK
export PHOENIX_EXTRA_POLICIES_FILE_OSX
export PHOENIX_EXTRA_POLICIES_FILE_OSX_INTEL
export PHOENIX_EXTRA_POLICIES_FILE_OSX_SILICON
export PHOENIX_EXTRA_POLICIES_FILE_WINDOWS

readonly PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_LINUX_FLATPAK="${DOVE_LINUX_FLATPAK_OUTPUTS}/policies"
readonly PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_LINUX_NONFLATPAK="${DOVE_LINUX_OUTPUTS}/policies"
readonly PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_OSX_INTEL="${DOVE_OSX_INTEL_OUTPUTS}"
readonly PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_OSX_SILICON="${DOVE_OSX_OUTPUTS}/macos"
readonly PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_WINDOWS="${DOVE_WINDOWS_OUTPUTS}/distribution"
export PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_LINUX_FLATPAK
export PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_LINUX_NONFLATPAK
export PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_OSX_INTEL
export PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_OSX_SILICON
export PHOENIX_EXTRA_POLICIES_OUTPUT_DIR_WINDOWS

readonly PHOENIX_LINUX_ONLY="${DOVE_LINUX_ONLY}"
readonly PHOENIX_LINUX_FLATPAK_ONLY="${DOVE_LINUX_FLATPAK_ONLY}"
readonly PHOENIX_OSX_ONLY="${DOVE_OSX_ONLY}"
readonly PHOENIX_OSX_INTEL_ONLY="${DOVE_OSX_INTEL_ONLY}"
readonly PHOENIX_WINDOWS_ONLY="${DOVE_WINDOWS_ONLY}"
export PHOENIX_LINUX_ONLY
export PHOENIX_LINUX_FLATPAK_ONLY
export PHOENIX_OSX_ONLY
export PHOENIX_OSX_INTEL_ONLY
export PHOENIX_WINDOWS_ONLY

readonly PHOENIX_LINUX="${DOVE_LINUX}"
readonly PHOENIX_LINUX_FLATPAK="${DOVE_LINUX_FLATPAK}"
readonly PHOENIX_OSX="${DOVE_OSX}"
readonly PHOENIX_OSX_INTEL="${DOVE_OSX_INTEL}"
readonly PHOENIX_WINDOWS="${DOVE_WINDOWS}"
export PHOENIX_LINUX
export PHOENIX_LINUX_FLATPAK
export PHOENIX_OSX
export PHOENIX_OSX_INTEL
export PHOENIX_WINDOWS

# Python
## https://docs.python.org/3/using/cmdline.html#environment-variables

## Disable JIT
readonly PYTHON_JIT=0
readonly PYTHON_PERF_JIT_SUPPORT=0
export PYTHON_JIT
export PYTHON_PERF_JIT_SUPPORT

## Disable remote debugging
readonly PYTHON_DISABLE_REMOTE_DEBUG=1
export PYTHON_DISABLE_REMOTE_DEBUG

## Enable performance optimizations
readonly PYTHONOPTIMIZE=1
export PYTHONOPTIMIZE
